# Generated by Django 5.0.7 on 2024-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='billing_zip',
            field=models.CharField(max_length=6),
        ),
    ]
